[package]
name = "e4docker"
version = "0.2.0"
edition = "2021"
authors = [ "Dorian Soru <doriansoru@gmail.com>"]

[dependencies]
configparser = "3.1.0"
dirs = "5.0.1"
fltk  = "^1.4"
round = "0.1.2"
image = "0.25.5"
fltk-grid = "0.4.1"
base64 = "0.22.1"

# Added to hide a terminal on Windows
[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[[bin]]
name = "e4docker"
windows_subsystem = "windows"
